# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# merge_map.py
# Created on: 2021-02-28 22:53:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: matching the GPS coordinate map with the most detailed administrative level of the world map
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
GPS1_shp = "D:\\Research\\WEBS\\Geo_data\\marshallian\\GPS1.shp"
GPS2_shp = "D:\\Research\\WEBS\\Geo_data\\marshallian\\GPS2.shp"
all_shp = "D:\\Research\\WEBS\\Geo_data\\city_map\\all.shp"
matched1_shp = "D:\\Research\\WEBS\\Geo_data\\marshallian\\matched1.shp"
matched2_shp = "D:\\Research\\WEBS\\Geo_data\\marshallian\\matched2.shp"
matched1_xls = "D:\\Research\\WEBS\\Geo_data\\marshallian\\matched1.xls"
matched2_xls = "D:\\Research\\WEBS\\Geo_data\\marshallian\\matched2.xls"

# Process: Merge: see the "merge_all" file

# Process: Spatial Join
arcpy.SpatialJoin_analysis(GPS1_shp, all_shp, matched1_shp, "JOIN_ONE_TO_MANY", "KEEP_ALL", "", "INTERSECT", "", "")
arcpy.SpatialJoin_analysis(GPS2_shp, all_shp, matched2_shp, "JOIN_ONE_TO_MANY", "KEEP_ALL", "", "INTERSECT", "", "")

# Process: Table To Excel
arcpy.TableToExcel_conversion(matched1_shp, matched1_xls, "NAME", "CODE")
arcpy.TableToExcel_conversion(matched2_shp, matched2_xls, "NAME", "CODE")

