# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2021-04-25 23:01:32.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.workspace = "D:\\Research\\WEBS\\ged201-dta"


# Process: XY table to point feature
x=2010
while x<2020:
    print str(x)
    arcpy.MakeXYEventLayer_management("D:\\Research\\WEBS\\ged201-dta\\GPS_"+str(x)+".csv", "longitude", "latitude", "D:\\Research\\WEBS\\ged201-dta\\conflict_gps_"+str(x), "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "")
    x=x+1

x=2010
while x<2020:
    print str(x)
    arcpy.CopyFeatures_management("D:\\Research\\WEBS\\ged201-dta\\conflict_gps_"+str(x), "D:\\Research\\WEBS\\ged201-dta\\conflict_"+str(x))
    x=x+1
    

# Process: spatial joining
all_city_erase_shp = "D:\\Research\\WEBS\\Geo_data\\nightlight_working_data\\all_city_erase.shp"

x=2010
while x<2020:
    print str(x)
    arcpy.SpatialJoin_analysis("D:\\Research\\WEBS\\ged201-dta\\conflict_"+str(x)+".shp", all_city_erase_shp, "D:\\Research\\WEBS\\ged201-dta\\conflict_WBES"+str(x), "JOIN_ONE_TO_MANY", "KEEP_ALL", "", "INTERSECT", "", "")
    x=x+1


# Process: Table To Excel
x=2010
while x<2020:
    print str(x)
    arcpy.TableToExcel_conversion("D:\\Research\\WEBS\\ged201-dta\\conflict_WBES"+str(x)+".shp", "D:\\Research\\WEBS\\ged201-dta\\conflict_WBES"+str(x)+".xls", "NAME", "CODE")
    x=x+1
